### PR TITLE
allow to use a different masking value than missing

### PR DESCRIPTION
**Pull request by Alexander-Barth**
Currently missing values (and fill values) are loaded as `missing` in Julia.  For some use cases, it is preferable to use different special values like `NaN`s (e.g. for GPUs, or interfacing with other C libraries). 

This PR allows the user to e.g. use `NaN` either per variable or per datasets.

What do you think?

### CODE REVIEW

**Comment by tcarion** [comment]
I think that's great, thank you for the PR !

**Comment by tcarion** [comment]
Sorry @Alexander-Barth, I think I forgot to merge this ! Could you reopen it ?

**Comment by Alexander-Barth** [comment]
Oh, sorry. I just synchronized my branch with your main. I forgot that this was not yet merged. I will re-open or make a new PR.

**Comment by Alexander-Barth** [comment]
OK, just clicking on reopen was enough to revive the PR :-)

**Review by tcarion — APPROVED** [review]

**Comment by Alexander-Barth** [comment]
Thanks and have a nice week-end!

**Pull request merged**
